model:
  name: 'resnet18'
  save_name: 'resnet18_mnist'

  params:
    model_params:
      num_classes: 10

    training_params:
      num_epochs: 5
      batch_size: 64
      num_workers: 2
      criterion: 'cross_entropy_loss'
      optimizer: 
        name: 'adamw'
        params:
          lr: 1e-3
          weight_decay: 1e-4
      scheduler: 
        name: 'exponential_lr'
        step: 3
        params:
          gamma: 0.9
